// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/ilovelili/dongfeng-core/services/proto/api.proto

package dongfeng_svc_core_server

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	dongfeng_protobuf "github.com/ilovelili/dongfeng-protobuf"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Api service

type ApiService interface {
	Login(ctx context.Context, in *dongfeng_protobuf.LoginRequest, opts ...client.CallOption) (*dongfeng_protobuf.LoginResponse, error)
	Dashboard(ctx context.Context, in *dongfeng_protobuf.DashboardRequest, opts ...client.CallOption) (*dongfeng_protobuf.DashboardResponse, error)
	UpdateUser(ctx context.Context, in *dongfeng_protobuf.UpdateUserRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateUserResponse, error)
	GetClasses(ctx context.Context, in *dongfeng_protobuf.GetClassRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetClassResponse, error)
	UpdateClasses(ctx context.Context, in *dongfeng_protobuf.UpdateClassRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateClassResponse, error)
	GetPupils(ctx context.Context, in *dongfeng_protobuf.GetPupilRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetPupilResponse, error)
	UpdatePupil(ctx context.Context, in *dongfeng_protobuf.UpdatePupilRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdatePupilResponse, error)
	UpdatePupils(ctx context.Context, in *dongfeng_protobuf.UpdatePupilRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdatePupilResponse, error)
	GetTeachers(ctx context.Context, in *dongfeng_protobuf.GetTeacherRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetTeacherResponse, error)
	UpdateTeacher(ctx context.Context, in *dongfeng_protobuf.UpdateTeacherRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateTeacherResponse, error)
	UpdateTeachers(ctx context.Context, in *dongfeng_protobuf.UpdateTeacherRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateTeacherResponse, error)
	GetAttendances(ctx context.Context, in *dongfeng_protobuf.GetAttendanceRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetAttendanceResponse, error)
	UpdateAttendance(ctx context.Context, in *dongfeng_protobuf.UpdateAttendanceRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateAttendanceResponse, error)
	UpdateAttendances(ctx context.Context, in *dongfeng_protobuf.UpdateAttendanceRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateAttendanceResponse, error)
	GetPhysiques(ctx context.Context, in *dongfeng_protobuf.GetPhysiqueRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetPhysiqueResponse, error)
	UpdatePhysique(ctx context.Context, in *dongfeng_protobuf.UpdatePhysiqueRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdatePhysiqueResponse, error)
	UpdatePhysiques(ctx context.Context, in *dongfeng_protobuf.UpdatePhysiqueRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdatePhysiqueResponse, error)
	GetAgeHeightWeightPMasters(ctx context.Context, in *dongfeng_protobuf.GetAgeHeightWeightPMasterRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetAgeHeightWeightPMasterResponse, error)
	GetAgeHeightWeightSDMasters(ctx context.Context, in *dongfeng_protobuf.GetAgeHeightWeightSDMasterRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetAgeHeightWeightSDMasterResponse, error)
	GetBMIMasters(ctx context.Context, in *dongfeng_protobuf.GetBMIMasterRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetBMIMasterResponse, error)
	GetHeightToWeightPMasters(ctx context.Context, in *dongfeng_protobuf.GetHeightToWeightPMasterRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetHeightToWeightPMasterResponse, error)
	GetHeightToWeightSDMasters(ctx context.Context, in *dongfeng_protobuf.GetHeightToWeightSDMasterRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetHeightToWeightSDMasterResponse, error)
	GetMenus(ctx context.Context, in *dongfeng_protobuf.GetMenuRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetMenuResponse, error)
	GetRecipes(ctx context.Context, in *dongfeng_protobuf.GetRecipeRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetRecipeResponse, error)
	GetIngredients(ctx context.Context, in *dongfeng_protobuf.GetIngredientRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetIngredientResponse, error)
	GetIngredientNames(ctx context.Context, in *dongfeng_protobuf.GetIngredientNameRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetIngredientNameResponse, error)
	UpdateIngredients(ctx context.Context, in *dongfeng_protobuf.UpdateIngredientRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateIngredientResponse, error)
	GetProcurements(ctx context.Context, in *dongfeng_protobuf.GetProcurementRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetProcurementResponse, error)
	UpdateProcurement(ctx context.Context, in *dongfeng_protobuf.UpdateProcurementRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateProcurementResponse, error)
	GetProfile(ctx context.Context, in *dongfeng_protobuf.GetProfileRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetProfileResponse, error)
	GetPrevProfile(ctx context.Context, in *dongfeng_protobuf.GetPrevOrNextProfileRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetPrevOrNextProfileResponse, error)
	GetNextProfile(ctx context.Context, in *dongfeng_protobuf.GetPrevOrNextProfileRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetPrevOrNextProfileResponse, error)
	GetProfiles(ctx context.Context, in *dongfeng_protobuf.GetProfilesRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetProfilesResponse, error)
	CreateProfile(ctx context.Context, in *dongfeng_protobuf.UpdateProfileRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateProfileResponse, error)
	UpdateProfile(ctx context.Context, in *dongfeng_protobuf.UpdateProfileRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateProfileResponse, error)
	DeleteProfile(ctx context.Context, in *dongfeng_protobuf.UpdateProfileRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateProfileResponse, error)
	GetEbooks(ctx context.Context, in *dongfeng_protobuf.GetEbooksRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetEbooksResponse, error)
	UpdateEbook(ctx context.Context, in *dongfeng_protobuf.UpdateEbookRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateEbookResponse, error)
	UpdateNotification(ctx context.Context, in *dongfeng_protobuf.UpdateNotificationRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateNotificationResponse, error)
	UpdateNotifications(ctx context.Context, in *dongfeng_protobuf.UpdateNotificationsRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateNotificationsResponse, error)
	GetRole(ctx context.Context, in *dongfeng_protobuf.GetRoleRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetRoleResponse, error)
	GetProfileTemplates(ctx context.Context, in *dongfeng_protobuf.GetProfileTemplatesRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetProfileTemplatesResponse, error)
}

type apiService struct {
	c    client.Client
	name string
}

func NewApiService(name string, c client.Client) ApiService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "dongfeng.svc.core.server"
	}
	return &apiService{
		c:    c,
		name: name,
	}
}

func (c *apiService) Login(ctx context.Context, in *dongfeng_protobuf.LoginRequest, opts ...client.CallOption) (*dongfeng_protobuf.LoginResponse, error) {
	req := c.c.NewRequest(c.name, "Api.Login", in)
	out := new(dongfeng_protobuf.LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) Dashboard(ctx context.Context, in *dongfeng_protobuf.DashboardRequest, opts ...client.CallOption) (*dongfeng_protobuf.DashboardResponse, error) {
	req := c.c.NewRequest(c.name, "Api.Dashboard", in)
	out := new(dongfeng_protobuf.DashboardResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) UpdateUser(ctx context.Context, in *dongfeng_protobuf.UpdateUserRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateUserResponse, error) {
	req := c.c.NewRequest(c.name, "Api.UpdateUser", in)
	out := new(dongfeng_protobuf.UpdateUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetClasses(ctx context.Context, in *dongfeng_protobuf.GetClassRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetClassResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetClasses", in)
	out := new(dongfeng_protobuf.GetClassResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) UpdateClasses(ctx context.Context, in *dongfeng_protobuf.UpdateClassRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateClassResponse, error) {
	req := c.c.NewRequest(c.name, "Api.UpdateClasses", in)
	out := new(dongfeng_protobuf.UpdateClassResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetPupils(ctx context.Context, in *dongfeng_protobuf.GetPupilRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetPupilResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetPupils", in)
	out := new(dongfeng_protobuf.GetPupilResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) UpdatePupil(ctx context.Context, in *dongfeng_protobuf.UpdatePupilRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdatePupilResponse, error) {
	req := c.c.NewRequest(c.name, "Api.UpdatePupil", in)
	out := new(dongfeng_protobuf.UpdatePupilResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) UpdatePupils(ctx context.Context, in *dongfeng_protobuf.UpdatePupilRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdatePupilResponse, error) {
	req := c.c.NewRequest(c.name, "Api.UpdatePupils", in)
	out := new(dongfeng_protobuf.UpdatePupilResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetTeachers(ctx context.Context, in *dongfeng_protobuf.GetTeacherRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetTeacherResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetTeachers", in)
	out := new(dongfeng_protobuf.GetTeacherResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) UpdateTeacher(ctx context.Context, in *dongfeng_protobuf.UpdateTeacherRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateTeacherResponse, error) {
	req := c.c.NewRequest(c.name, "Api.UpdateTeacher", in)
	out := new(dongfeng_protobuf.UpdateTeacherResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) UpdateTeachers(ctx context.Context, in *dongfeng_protobuf.UpdateTeacherRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateTeacherResponse, error) {
	req := c.c.NewRequest(c.name, "Api.UpdateTeachers", in)
	out := new(dongfeng_protobuf.UpdateTeacherResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetAttendances(ctx context.Context, in *dongfeng_protobuf.GetAttendanceRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetAttendanceResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetAttendances", in)
	out := new(dongfeng_protobuf.GetAttendanceResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) UpdateAttendance(ctx context.Context, in *dongfeng_protobuf.UpdateAttendanceRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateAttendanceResponse, error) {
	req := c.c.NewRequest(c.name, "Api.UpdateAttendance", in)
	out := new(dongfeng_protobuf.UpdateAttendanceResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) UpdateAttendances(ctx context.Context, in *dongfeng_protobuf.UpdateAttendanceRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateAttendanceResponse, error) {
	req := c.c.NewRequest(c.name, "Api.UpdateAttendances", in)
	out := new(dongfeng_protobuf.UpdateAttendanceResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetPhysiques(ctx context.Context, in *dongfeng_protobuf.GetPhysiqueRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetPhysiqueResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetPhysiques", in)
	out := new(dongfeng_protobuf.GetPhysiqueResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) UpdatePhysique(ctx context.Context, in *dongfeng_protobuf.UpdatePhysiqueRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdatePhysiqueResponse, error) {
	req := c.c.NewRequest(c.name, "Api.UpdatePhysique", in)
	out := new(dongfeng_protobuf.UpdatePhysiqueResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) UpdatePhysiques(ctx context.Context, in *dongfeng_protobuf.UpdatePhysiqueRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdatePhysiqueResponse, error) {
	req := c.c.NewRequest(c.name, "Api.UpdatePhysiques", in)
	out := new(dongfeng_protobuf.UpdatePhysiqueResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetAgeHeightWeightPMasters(ctx context.Context, in *dongfeng_protobuf.GetAgeHeightWeightPMasterRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetAgeHeightWeightPMasterResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetAgeHeightWeightPMasters", in)
	out := new(dongfeng_protobuf.GetAgeHeightWeightPMasterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetAgeHeightWeightSDMasters(ctx context.Context, in *dongfeng_protobuf.GetAgeHeightWeightSDMasterRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetAgeHeightWeightSDMasterResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetAgeHeightWeightSDMasters", in)
	out := new(dongfeng_protobuf.GetAgeHeightWeightSDMasterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetBMIMasters(ctx context.Context, in *dongfeng_protobuf.GetBMIMasterRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetBMIMasterResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetBMIMasters", in)
	out := new(dongfeng_protobuf.GetBMIMasterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetHeightToWeightPMasters(ctx context.Context, in *dongfeng_protobuf.GetHeightToWeightPMasterRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetHeightToWeightPMasterResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetHeightToWeightPMasters", in)
	out := new(dongfeng_protobuf.GetHeightToWeightPMasterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetHeightToWeightSDMasters(ctx context.Context, in *dongfeng_protobuf.GetHeightToWeightSDMasterRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetHeightToWeightSDMasterResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetHeightToWeightSDMasters", in)
	out := new(dongfeng_protobuf.GetHeightToWeightSDMasterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetMenus(ctx context.Context, in *dongfeng_protobuf.GetMenuRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetMenuResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetMenus", in)
	out := new(dongfeng_protobuf.GetMenuResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetRecipes(ctx context.Context, in *dongfeng_protobuf.GetRecipeRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetRecipeResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetRecipes", in)
	out := new(dongfeng_protobuf.GetRecipeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetIngredients(ctx context.Context, in *dongfeng_protobuf.GetIngredientRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetIngredientResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetIngredients", in)
	out := new(dongfeng_protobuf.GetIngredientResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetIngredientNames(ctx context.Context, in *dongfeng_protobuf.GetIngredientNameRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetIngredientNameResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetIngredientNames", in)
	out := new(dongfeng_protobuf.GetIngredientNameResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) UpdateIngredients(ctx context.Context, in *dongfeng_protobuf.UpdateIngredientRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateIngredientResponse, error) {
	req := c.c.NewRequest(c.name, "Api.UpdateIngredients", in)
	out := new(dongfeng_protobuf.UpdateIngredientResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetProcurements(ctx context.Context, in *dongfeng_protobuf.GetProcurementRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetProcurementResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetProcurements", in)
	out := new(dongfeng_protobuf.GetProcurementResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) UpdateProcurement(ctx context.Context, in *dongfeng_protobuf.UpdateProcurementRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateProcurementResponse, error) {
	req := c.c.NewRequest(c.name, "Api.UpdateProcurement", in)
	out := new(dongfeng_protobuf.UpdateProcurementResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetProfile(ctx context.Context, in *dongfeng_protobuf.GetProfileRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetProfileResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetProfile", in)
	out := new(dongfeng_protobuf.GetProfileResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetPrevProfile(ctx context.Context, in *dongfeng_protobuf.GetPrevOrNextProfileRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetPrevOrNextProfileResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetPrevProfile", in)
	out := new(dongfeng_protobuf.GetPrevOrNextProfileResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetNextProfile(ctx context.Context, in *dongfeng_protobuf.GetPrevOrNextProfileRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetPrevOrNextProfileResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetNextProfile", in)
	out := new(dongfeng_protobuf.GetPrevOrNextProfileResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetProfiles(ctx context.Context, in *dongfeng_protobuf.GetProfilesRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetProfilesResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetProfiles", in)
	out := new(dongfeng_protobuf.GetProfilesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) CreateProfile(ctx context.Context, in *dongfeng_protobuf.UpdateProfileRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateProfileResponse, error) {
	req := c.c.NewRequest(c.name, "Api.CreateProfile", in)
	out := new(dongfeng_protobuf.UpdateProfileResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) UpdateProfile(ctx context.Context, in *dongfeng_protobuf.UpdateProfileRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateProfileResponse, error) {
	req := c.c.NewRequest(c.name, "Api.UpdateProfile", in)
	out := new(dongfeng_protobuf.UpdateProfileResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) DeleteProfile(ctx context.Context, in *dongfeng_protobuf.UpdateProfileRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateProfileResponse, error) {
	req := c.c.NewRequest(c.name, "Api.DeleteProfile", in)
	out := new(dongfeng_protobuf.UpdateProfileResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetEbooks(ctx context.Context, in *dongfeng_protobuf.GetEbooksRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetEbooksResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetEbooks", in)
	out := new(dongfeng_protobuf.GetEbooksResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) UpdateEbook(ctx context.Context, in *dongfeng_protobuf.UpdateEbookRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateEbookResponse, error) {
	req := c.c.NewRequest(c.name, "Api.UpdateEbook", in)
	out := new(dongfeng_protobuf.UpdateEbookResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) UpdateNotification(ctx context.Context, in *dongfeng_protobuf.UpdateNotificationRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateNotificationResponse, error) {
	req := c.c.NewRequest(c.name, "Api.UpdateNotification", in)
	out := new(dongfeng_protobuf.UpdateNotificationResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) UpdateNotifications(ctx context.Context, in *dongfeng_protobuf.UpdateNotificationsRequest, opts ...client.CallOption) (*dongfeng_protobuf.UpdateNotificationsResponse, error) {
	req := c.c.NewRequest(c.name, "Api.UpdateNotifications", in)
	out := new(dongfeng_protobuf.UpdateNotificationsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetRole(ctx context.Context, in *dongfeng_protobuf.GetRoleRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetRoleResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetRole", in)
	out := new(dongfeng_protobuf.GetRoleResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) GetProfileTemplates(ctx context.Context, in *dongfeng_protobuf.GetProfileTemplatesRequest, opts ...client.CallOption) (*dongfeng_protobuf.GetProfileTemplatesResponse, error) {
	req := c.c.NewRequest(c.name, "Api.GetProfileTemplates", in)
	out := new(dongfeng_protobuf.GetProfileTemplatesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Api service

type ApiHandler interface {
	Login(context.Context, *dongfeng_protobuf.LoginRequest, *dongfeng_protobuf.LoginResponse) error
	Dashboard(context.Context, *dongfeng_protobuf.DashboardRequest, *dongfeng_protobuf.DashboardResponse) error
	UpdateUser(context.Context, *dongfeng_protobuf.UpdateUserRequest, *dongfeng_protobuf.UpdateUserResponse) error
	GetClasses(context.Context, *dongfeng_protobuf.GetClassRequest, *dongfeng_protobuf.GetClassResponse) error
	UpdateClasses(context.Context, *dongfeng_protobuf.UpdateClassRequest, *dongfeng_protobuf.UpdateClassResponse) error
	GetPupils(context.Context, *dongfeng_protobuf.GetPupilRequest, *dongfeng_protobuf.GetPupilResponse) error
	UpdatePupil(context.Context, *dongfeng_protobuf.UpdatePupilRequest, *dongfeng_protobuf.UpdatePupilResponse) error
	UpdatePupils(context.Context, *dongfeng_protobuf.UpdatePupilRequest, *dongfeng_protobuf.UpdatePupilResponse) error
	GetTeachers(context.Context, *dongfeng_protobuf.GetTeacherRequest, *dongfeng_protobuf.GetTeacherResponse) error
	UpdateTeacher(context.Context, *dongfeng_protobuf.UpdateTeacherRequest, *dongfeng_protobuf.UpdateTeacherResponse) error
	UpdateTeachers(context.Context, *dongfeng_protobuf.UpdateTeacherRequest, *dongfeng_protobuf.UpdateTeacherResponse) error
	GetAttendances(context.Context, *dongfeng_protobuf.GetAttendanceRequest, *dongfeng_protobuf.GetAttendanceResponse) error
	UpdateAttendance(context.Context, *dongfeng_protobuf.UpdateAttendanceRequest, *dongfeng_protobuf.UpdateAttendanceResponse) error
	UpdateAttendances(context.Context, *dongfeng_protobuf.UpdateAttendanceRequest, *dongfeng_protobuf.UpdateAttendanceResponse) error
	GetPhysiques(context.Context, *dongfeng_protobuf.GetPhysiqueRequest, *dongfeng_protobuf.GetPhysiqueResponse) error
	UpdatePhysique(context.Context, *dongfeng_protobuf.UpdatePhysiqueRequest, *dongfeng_protobuf.UpdatePhysiqueResponse) error
	UpdatePhysiques(context.Context, *dongfeng_protobuf.UpdatePhysiqueRequest, *dongfeng_protobuf.UpdatePhysiqueResponse) error
	GetAgeHeightWeightPMasters(context.Context, *dongfeng_protobuf.GetAgeHeightWeightPMasterRequest, *dongfeng_protobuf.GetAgeHeightWeightPMasterResponse) error
	GetAgeHeightWeightSDMasters(context.Context, *dongfeng_protobuf.GetAgeHeightWeightSDMasterRequest, *dongfeng_protobuf.GetAgeHeightWeightSDMasterResponse) error
	GetBMIMasters(context.Context, *dongfeng_protobuf.GetBMIMasterRequest, *dongfeng_protobuf.GetBMIMasterResponse) error
	GetHeightToWeightPMasters(context.Context, *dongfeng_protobuf.GetHeightToWeightPMasterRequest, *dongfeng_protobuf.GetHeightToWeightPMasterResponse) error
	GetHeightToWeightSDMasters(context.Context, *dongfeng_protobuf.GetHeightToWeightSDMasterRequest, *dongfeng_protobuf.GetHeightToWeightSDMasterResponse) error
	GetMenus(context.Context, *dongfeng_protobuf.GetMenuRequest, *dongfeng_protobuf.GetMenuResponse) error
	GetRecipes(context.Context, *dongfeng_protobuf.GetRecipeRequest, *dongfeng_protobuf.GetRecipeResponse) error
	GetIngredients(context.Context, *dongfeng_protobuf.GetIngredientRequest, *dongfeng_protobuf.GetIngredientResponse) error
	GetIngredientNames(context.Context, *dongfeng_protobuf.GetIngredientNameRequest, *dongfeng_protobuf.GetIngredientNameResponse) error
	UpdateIngredients(context.Context, *dongfeng_protobuf.UpdateIngredientRequest, *dongfeng_protobuf.UpdateIngredientResponse) error
	GetProcurements(context.Context, *dongfeng_protobuf.GetProcurementRequest, *dongfeng_protobuf.GetProcurementResponse) error
	UpdateProcurement(context.Context, *dongfeng_protobuf.UpdateProcurementRequest, *dongfeng_protobuf.UpdateProcurementResponse) error
	GetProfile(context.Context, *dongfeng_protobuf.GetProfileRequest, *dongfeng_protobuf.GetProfileResponse) error
	GetPrevProfile(context.Context, *dongfeng_protobuf.GetPrevOrNextProfileRequest, *dongfeng_protobuf.GetPrevOrNextProfileResponse) error
	GetNextProfile(context.Context, *dongfeng_protobuf.GetPrevOrNextProfileRequest, *dongfeng_protobuf.GetPrevOrNextProfileResponse) error
	GetProfiles(context.Context, *dongfeng_protobuf.GetProfilesRequest, *dongfeng_protobuf.GetProfilesResponse) error
	CreateProfile(context.Context, *dongfeng_protobuf.UpdateProfileRequest, *dongfeng_protobuf.UpdateProfileResponse) error
	UpdateProfile(context.Context, *dongfeng_protobuf.UpdateProfileRequest, *dongfeng_protobuf.UpdateProfileResponse) error
	DeleteProfile(context.Context, *dongfeng_protobuf.UpdateProfileRequest, *dongfeng_protobuf.UpdateProfileResponse) error
	GetEbooks(context.Context, *dongfeng_protobuf.GetEbooksRequest, *dongfeng_protobuf.GetEbooksResponse) error
	UpdateEbook(context.Context, *dongfeng_protobuf.UpdateEbookRequest, *dongfeng_protobuf.UpdateEbookResponse) error
	UpdateNotification(context.Context, *dongfeng_protobuf.UpdateNotificationRequest, *dongfeng_protobuf.UpdateNotificationResponse) error
	UpdateNotifications(context.Context, *dongfeng_protobuf.UpdateNotificationsRequest, *dongfeng_protobuf.UpdateNotificationsResponse) error
	GetRole(context.Context, *dongfeng_protobuf.GetRoleRequest, *dongfeng_protobuf.GetRoleResponse) error
	GetProfileTemplates(context.Context, *dongfeng_protobuf.GetProfileTemplatesRequest, *dongfeng_protobuf.GetProfileTemplatesResponse) error
}

func RegisterApiHandler(s server.Server, hdlr ApiHandler, opts ...server.HandlerOption) error {
	type api interface {
		Login(ctx context.Context, in *dongfeng_protobuf.LoginRequest, out *dongfeng_protobuf.LoginResponse) error
		Dashboard(ctx context.Context, in *dongfeng_protobuf.DashboardRequest, out *dongfeng_protobuf.DashboardResponse) error
		UpdateUser(ctx context.Context, in *dongfeng_protobuf.UpdateUserRequest, out *dongfeng_protobuf.UpdateUserResponse) error
		GetClasses(ctx context.Context, in *dongfeng_protobuf.GetClassRequest, out *dongfeng_protobuf.GetClassResponse) error
		UpdateClasses(ctx context.Context, in *dongfeng_protobuf.UpdateClassRequest, out *dongfeng_protobuf.UpdateClassResponse) error
		GetPupils(ctx context.Context, in *dongfeng_protobuf.GetPupilRequest, out *dongfeng_protobuf.GetPupilResponse) error
		UpdatePupil(ctx context.Context, in *dongfeng_protobuf.UpdatePupilRequest, out *dongfeng_protobuf.UpdatePupilResponse) error
		UpdatePupils(ctx context.Context, in *dongfeng_protobuf.UpdatePupilRequest, out *dongfeng_protobuf.UpdatePupilResponse) error
		GetTeachers(ctx context.Context, in *dongfeng_protobuf.GetTeacherRequest, out *dongfeng_protobuf.GetTeacherResponse) error
		UpdateTeacher(ctx context.Context, in *dongfeng_protobuf.UpdateTeacherRequest, out *dongfeng_protobuf.UpdateTeacherResponse) error
		UpdateTeachers(ctx context.Context, in *dongfeng_protobuf.UpdateTeacherRequest, out *dongfeng_protobuf.UpdateTeacherResponse) error
		GetAttendances(ctx context.Context, in *dongfeng_protobuf.GetAttendanceRequest, out *dongfeng_protobuf.GetAttendanceResponse) error
		UpdateAttendance(ctx context.Context, in *dongfeng_protobuf.UpdateAttendanceRequest, out *dongfeng_protobuf.UpdateAttendanceResponse) error
		UpdateAttendances(ctx context.Context, in *dongfeng_protobuf.UpdateAttendanceRequest, out *dongfeng_protobuf.UpdateAttendanceResponse) error
		GetPhysiques(ctx context.Context, in *dongfeng_protobuf.GetPhysiqueRequest, out *dongfeng_protobuf.GetPhysiqueResponse) error
		UpdatePhysique(ctx context.Context, in *dongfeng_protobuf.UpdatePhysiqueRequest, out *dongfeng_protobuf.UpdatePhysiqueResponse) error
		UpdatePhysiques(ctx context.Context, in *dongfeng_protobuf.UpdatePhysiqueRequest, out *dongfeng_protobuf.UpdatePhysiqueResponse) error
		GetAgeHeightWeightPMasters(ctx context.Context, in *dongfeng_protobuf.GetAgeHeightWeightPMasterRequest, out *dongfeng_protobuf.GetAgeHeightWeightPMasterResponse) error
		GetAgeHeightWeightSDMasters(ctx context.Context, in *dongfeng_protobuf.GetAgeHeightWeightSDMasterRequest, out *dongfeng_protobuf.GetAgeHeightWeightSDMasterResponse) error
		GetBMIMasters(ctx context.Context, in *dongfeng_protobuf.GetBMIMasterRequest, out *dongfeng_protobuf.GetBMIMasterResponse) error
		GetHeightToWeightPMasters(ctx context.Context, in *dongfeng_protobuf.GetHeightToWeightPMasterRequest, out *dongfeng_protobuf.GetHeightToWeightPMasterResponse) error
		GetHeightToWeightSDMasters(ctx context.Context, in *dongfeng_protobuf.GetHeightToWeightSDMasterRequest, out *dongfeng_protobuf.GetHeightToWeightSDMasterResponse) error
		GetMenus(ctx context.Context, in *dongfeng_protobuf.GetMenuRequest, out *dongfeng_protobuf.GetMenuResponse) error
		GetRecipes(ctx context.Context, in *dongfeng_protobuf.GetRecipeRequest, out *dongfeng_protobuf.GetRecipeResponse) error
		GetIngredients(ctx context.Context, in *dongfeng_protobuf.GetIngredientRequest, out *dongfeng_protobuf.GetIngredientResponse) error
		GetIngredientNames(ctx context.Context, in *dongfeng_protobuf.GetIngredientNameRequest, out *dongfeng_protobuf.GetIngredientNameResponse) error
		UpdateIngredients(ctx context.Context, in *dongfeng_protobuf.UpdateIngredientRequest, out *dongfeng_protobuf.UpdateIngredientResponse) error
		GetProcurements(ctx context.Context, in *dongfeng_protobuf.GetProcurementRequest, out *dongfeng_protobuf.GetProcurementResponse) error
		UpdateProcurement(ctx context.Context, in *dongfeng_protobuf.UpdateProcurementRequest, out *dongfeng_protobuf.UpdateProcurementResponse) error
		GetProfile(ctx context.Context, in *dongfeng_protobuf.GetProfileRequest, out *dongfeng_protobuf.GetProfileResponse) error
		GetPrevProfile(ctx context.Context, in *dongfeng_protobuf.GetPrevOrNextProfileRequest, out *dongfeng_protobuf.GetPrevOrNextProfileResponse) error
		GetNextProfile(ctx context.Context, in *dongfeng_protobuf.GetPrevOrNextProfileRequest, out *dongfeng_protobuf.GetPrevOrNextProfileResponse) error
		GetProfiles(ctx context.Context, in *dongfeng_protobuf.GetProfilesRequest, out *dongfeng_protobuf.GetProfilesResponse) error
		CreateProfile(ctx context.Context, in *dongfeng_protobuf.UpdateProfileRequest, out *dongfeng_protobuf.UpdateProfileResponse) error
		UpdateProfile(ctx context.Context, in *dongfeng_protobuf.UpdateProfileRequest, out *dongfeng_protobuf.UpdateProfileResponse) error
		DeleteProfile(ctx context.Context, in *dongfeng_protobuf.UpdateProfileRequest, out *dongfeng_protobuf.UpdateProfileResponse) error
		GetEbooks(ctx context.Context, in *dongfeng_protobuf.GetEbooksRequest, out *dongfeng_protobuf.GetEbooksResponse) error
		UpdateEbook(ctx context.Context, in *dongfeng_protobuf.UpdateEbookRequest, out *dongfeng_protobuf.UpdateEbookResponse) error
		UpdateNotification(ctx context.Context, in *dongfeng_protobuf.UpdateNotificationRequest, out *dongfeng_protobuf.UpdateNotificationResponse) error
		UpdateNotifications(ctx context.Context, in *dongfeng_protobuf.UpdateNotificationsRequest, out *dongfeng_protobuf.UpdateNotificationsResponse) error
		GetRole(ctx context.Context, in *dongfeng_protobuf.GetRoleRequest, out *dongfeng_protobuf.GetRoleResponse) error
		GetProfileTemplates(ctx context.Context, in *dongfeng_protobuf.GetProfileTemplatesRequest, out *dongfeng_protobuf.GetProfileTemplatesResponse) error
	}
	type Api struct {
		api
	}
	h := &apiHandler{hdlr}
	return s.Handle(s.NewHandler(&Api{h}, opts...))
}

type apiHandler struct {
	ApiHandler
}

func (h *apiHandler) Login(ctx context.Context, in *dongfeng_protobuf.LoginRequest, out *dongfeng_protobuf.LoginResponse) error {
	return h.ApiHandler.Login(ctx, in, out)
}

func (h *apiHandler) Dashboard(ctx context.Context, in *dongfeng_protobuf.DashboardRequest, out *dongfeng_protobuf.DashboardResponse) error {
	return h.ApiHandler.Dashboard(ctx, in, out)
}

func (h *apiHandler) UpdateUser(ctx context.Context, in *dongfeng_protobuf.UpdateUserRequest, out *dongfeng_protobuf.UpdateUserResponse) error {
	return h.ApiHandler.UpdateUser(ctx, in, out)
}

func (h *apiHandler) GetClasses(ctx context.Context, in *dongfeng_protobuf.GetClassRequest, out *dongfeng_protobuf.GetClassResponse) error {
	return h.ApiHandler.GetClasses(ctx, in, out)
}

func (h *apiHandler) UpdateClasses(ctx context.Context, in *dongfeng_protobuf.UpdateClassRequest, out *dongfeng_protobuf.UpdateClassResponse) error {
	return h.ApiHandler.UpdateClasses(ctx, in, out)
}

func (h *apiHandler) GetPupils(ctx context.Context, in *dongfeng_protobuf.GetPupilRequest, out *dongfeng_protobuf.GetPupilResponse) error {
	return h.ApiHandler.GetPupils(ctx, in, out)
}

func (h *apiHandler) UpdatePupil(ctx context.Context, in *dongfeng_protobuf.UpdatePupilRequest, out *dongfeng_protobuf.UpdatePupilResponse) error {
	return h.ApiHandler.UpdatePupil(ctx, in, out)
}

func (h *apiHandler) UpdatePupils(ctx context.Context, in *dongfeng_protobuf.UpdatePupilRequest, out *dongfeng_protobuf.UpdatePupilResponse) error {
	return h.ApiHandler.UpdatePupils(ctx, in, out)
}

func (h *apiHandler) GetTeachers(ctx context.Context, in *dongfeng_protobuf.GetTeacherRequest, out *dongfeng_protobuf.GetTeacherResponse) error {
	return h.ApiHandler.GetTeachers(ctx, in, out)
}

func (h *apiHandler) UpdateTeacher(ctx context.Context, in *dongfeng_protobuf.UpdateTeacherRequest, out *dongfeng_protobuf.UpdateTeacherResponse) error {
	return h.ApiHandler.UpdateTeacher(ctx, in, out)
}

func (h *apiHandler) UpdateTeachers(ctx context.Context, in *dongfeng_protobuf.UpdateTeacherRequest, out *dongfeng_protobuf.UpdateTeacherResponse) error {
	return h.ApiHandler.UpdateTeachers(ctx, in, out)
}

func (h *apiHandler) GetAttendances(ctx context.Context, in *dongfeng_protobuf.GetAttendanceRequest, out *dongfeng_protobuf.GetAttendanceResponse) error {
	return h.ApiHandler.GetAttendances(ctx, in, out)
}

func (h *apiHandler) UpdateAttendance(ctx context.Context, in *dongfeng_protobuf.UpdateAttendanceRequest, out *dongfeng_protobuf.UpdateAttendanceResponse) error {
	return h.ApiHandler.UpdateAttendance(ctx, in, out)
}

func (h *apiHandler) UpdateAttendances(ctx context.Context, in *dongfeng_protobuf.UpdateAttendanceRequest, out *dongfeng_protobuf.UpdateAttendanceResponse) error {
	return h.ApiHandler.UpdateAttendances(ctx, in, out)
}

func (h *apiHandler) GetPhysiques(ctx context.Context, in *dongfeng_protobuf.GetPhysiqueRequest, out *dongfeng_protobuf.GetPhysiqueResponse) error {
	return h.ApiHandler.GetPhysiques(ctx, in, out)
}

func (h *apiHandler) UpdatePhysique(ctx context.Context, in *dongfeng_protobuf.UpdatePhysiqueRequest, out *dongfeng_protobuf.UpdatePhysiqueResponse) error {
	return h.ApiHandler.UpdatePhysique(ctx, in, out)
}

func (h *apiHandler) UpdatePhysiques(ctx context.Context, in *dongfeng_protobuf.UpdatePhysiqueRequest, out *dongfeng_protobuf.UpdatePhysiqueResponse) error {
	return h.ApiHandler.UpdatePhysiques(ctx, in, out)
}

func (h *apiHandler) GetAgeHeightWeightPMasters(ctx context.Context, in *dongfeng_protobuf.GetAgeHeightWeightPMasterRequest, out *dongfeng_protobuf.GetAgeHeightWeightPMasterResponse) error {
	return h.ApiHandler.GetAgeHeightWeightPMasters(ctx, in, out)
}

func (h *apiHandler) GetAgeHeightWeightSDMasters(ctx context.Context, in *dongfeng_protobuf.GetAgeHeightWeightSDMasterRequest, out *dongfeng_protobuf.GetAgeHeightWeightSDMasterResponse) error {
	return h.ApiHandler.GetAgeHeightWeightSDMasters(ctx, in, out)
}

func (h *apiHandler) GetBMIMasters(ctx context.Context, in *dongfeng_protobuf.GetBMIMasterRequest, out *dongfeng_protobuf.GetBMIMasterResponse) error {
	return h.ApiHandler.GetBMIMasters(ctx, in, out)
}

func (h *apiHandler) GetHeightToWeightPMasters(ctx context.Context, in *dongfeng_protobuf.GetHeightToWeightPMasterRequest, out *dongfeng_protobuf.GetHeightToWeightPMasterResponse) error {
	return h.ApiHandler.GetHeightToWeightPMasters(ctx, in, out)
}

func (h *apiHandler) GetHeightToWeightSDMasters(ctx context.Context, in *dongfeng_protobuf.GetHeightToWeightSDMasterRequest, out *dongfeng_protobuf.GetHeightToWeightSDMasterResponse) error {
	return h.ApiHandler.GetHeightToWeightSDMasters(ctx, in, out)
}

func (h *apiHandler) GetMenus(ctx context.Context, in *dongfeng_protobuf.GetMenuRequest, out *dongfeng_protobuf.GetMenuResponse) error {
	return h.ApiHandler.GetMenus(ctx, in, out)
}

func (h *apiHandler) GetRecipes(ctx context.Context, in *dongfeng_protobuf.GetRecipeRequest, out *dongfeng_protobuf.GetRecipeResponse) error {
	return h.ApiHandler.GetRecipes(ctx, in, out)
}

func (h *apiHandler) GetIngredients(ctx context.Context, in *dongfeng_protobuf.GetIngredientRequest, out *dongfeng_protobuf.GetIngredientResponse) error {
	return h.ApiHandler.GetIngredients(ctx, in, out)
}

func (h *apiHandler) GetIngredientNames(ctx context.Context, in *dongfeng_protobuf.GetIngredientNameRequest, out *dongfeng_protobuf.GetIngredientNameResponse) error {
	return h.ApiHandler.GetIngredientNames(ctx, in, out)
}

func (h *apiHandler) UpdateIngredients(ctx context.Context, in *dongfeng_protobuf.UpdateIngredientRequest, out *dongfeng_protobuf.UpdateIngredientResponse) error {
	return h.ApiHandler.UpdateIngredients(ctx, in, out)
}

func (h *apiHandler) GetProcurements(ctx context.Context, in *dongfeng_protobuf.GetProcurementRequest, out *dongfeng_protobuf.GetProcurementResponse) error {
	return h.ApiHandler.GetProcurements(ctx, in, out)
}

func (h *apiHandler) UpdateProcurement(ctx context.Context, in *dongfeng_protobuf.UpdateProcurementRequest, out *dongfeng_protobuf.UpdateProcurementResponse) error {
	return h.ApiHandler.UpdateProcurement(ctx, in, out)
}

func (h *apiHandler) GetProfile(ctx context.Context, in *dongfeng_protobuf.GetProfileRequest, out *dongfeng_protobuf.GetProfileResponse) error {
	return h.ApiHandler.GetProfile(ctx, in, out)
}

func (h *apiHandler) GetPrevProfile(ctx context.Context, in *dongfeng_protobuf.GetPrevOrNextProfileRequest, out *dongfeng_protobuf.GetPrevOrNextProfileResponse) error {
	return h.ApiHandler.GetPrevProfile(ctx, in, out)
}

func (h *apiHandler) GetNextProfile(ctx context.Context, in *dongfeng_protobuf.GetPrevOrNextProfileRequest, out *dongfeng_protobuf.GetPrevOrNextProfileResponse) error {
	return h.ApiHandler.GetNextProfile(ctx, in, out)
}

func (h *apiHandler) GetProfiles(ctx context.Context, in *dongfeng_protobuf.GetProfilesRequest, out *dongfeng_protobuf.GetProfilesResponse) error {
	return h.ApiHandler.GetProfiles(ctx, in, out)
}

func (h *apiHandler) CreateProfile(ctx context.Context, in *dongfeng_protobuf.UpdateProfileRequest, out *dongfeng_protobuf.UpdateProfileResponse) error {
	return h.ApiHandler.CreateProfile(ctx, in, out)
}

func (h *apiHandler) UpdateProfile(ctx context.Context, in *dongfeng_protobuf.UpdateProfileRequest, out *dongfeng_protobuf.UpdateProfileResponse) error {
	return h.ApiHandler.UpdateProfile(ctx, in, out)
}

func (h *apiHandler) DeleteProfile(ctx context.Context, in *dongfeng_protobuf.UpdateProfileRequest, out *dongfeng_protobuf.UpdateProfileResponse) error {
	return h.ApiHandler.DeleteProfile(ctx, in, out)
}

func (h *apiHandler) GetEbooks(ctx context.Context, in *dongfeng_protobuf.GetEbooksRequest, out *dongfeng_protobuf.GetEbooksResponse) error {
	return h.ApiHandler.GetEbooks(ctx, in, out)
}

func (h *apiHandler) UpdateEbook(ctx context.Context, in *dongfeng_protobuf.UpdateEbookRequest, out *dongfeng_protobuf.UpdateEbookResponse) error {
	return h.ApiHandler.UpdateEbook(ctx, in, out)
}

func (h *apiHandler) UpdateNotification(ctx context.Context, in *dongfeng_protobuf.UpdateNotificationRequest, out *dongfeng_protobuf.UpdateNotificationResponse) error {
	return h.ApiHandler.UpdateNotification(ctx, in, out)
}

func (h *apiHandler) UpdateNotifications(ctx context.Context, in *dongfeng_protobuf.UpdateNotificationsRequest, out *dongfeng_protobuf.UpdateNotificationsResponse) error {
	return h.ApiHandler.UpdateNotifications(ctx, in, out)
}

func (h *apiHandler) GetRole(ctx context.Context, in *dongfeng_protobuf.GetRoleRequest, out *dongfeng_protobuf.GetRoleResponse) error {
	return h.ApiHandler.GetRole(ctx, in, out)
}

func (h *apiHandler) GetProfileTemplates(ctx context.Context, in *dongfeng_protobuf.GetProfileTemplatesRequest, out *dongfeng_protobuf.GetProfileTemplatesResponse) error {
	return h.ApiHandler.GetProfileTemplates(ctx, in, out)
}
