// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/ilovelili/dongfeng/core/services/proto/api.proto

package dongfeng_svc_core_server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HealthcheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthcheckRequest) Reset()         { *m = HealthcheckRequest{} }
func (m *HealthcheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthcheckRequest) ProtoMessage()    {}
func (*HealthcheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_385bde6a5715af9a, []int{0}
}
func (m *HealthcheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthcheckRequest.Unmarshal(m, b)
}
func (m *HealthcheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthcheckRequest.Marshal(b, m, deterministic)
}
func (dst *HealthcheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthcheckRequest.Merge(dst, src)
}
func (m *HealthcheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthcheckRequest.Size(m)
}
func (m *HealthcheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthcheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthcheckRequest proto.InternalMessageInfo

type HealthcheckResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthcheckResponse) Reset()         { *m = HealthcheckResponse{} }
func (m *HealthcheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthcheckResponse) ProtoMessage()    {}
func (*HealthcheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_385bde6a5715af9a, []int{1}
}
func (m *HealthcheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthcheckResponse.Unmarshal(m, b)
}
func (m *HealthcheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthcheckResponse.Marshal(b, m, deterministic)
}
func (dst *HealthcheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthcheckResponse.Merge(dst, src)
}
func (m *HealthcheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthcheckResponse.Size(m)
}
func (m *HealthcheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthcheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthcheckResponse proto.InternalMessageInfo

func (m *HealthcheckResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LoginRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_385bde6a5715af9a, []int{2}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

type LoginResponse struct {
	Version              string       `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	User                 *User        `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	SystemBroadcasting   []*Operation `protobuf:"bytes,3,rep,name=system_broadcasting,json=systemBroadcasting,proto3" json:"system_broadcasting,omitempty"`
	UserUpdates          []*Operation `protobuf:"bytes,4,rep,name=user_updates,json=userUpdates,proto3" json:"user_updates,omitempty"`
	FriendUpdates        []*Operation `protobuf:"bytes,5,rep,name=friend_updates,json=friendUpdates,proto3" json:"friend_updates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_385bde6a5715af9a, []int{3}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginResponse) GetSystemBroadcasting() []*Operation {
	if m != nil {
		return m.SystemBroadcasting
	}
	return nil
}

func (m *LoginResponse) GetUserUpdates() []*Operation {
	if m != nil {
		return m.UserUpdates
	}
	return nil
}

func (m *LoginResponse) GetFriendUpdates() []*Operation {
	if m != nil {
		return m.FriendUpdates
	}
	return nil
}

// User user profile
type User struct {
	Newuser              bool       `protobuf:"varint,1,opt,name=newuser,proto3" json:"newuser,omitempty"`
	Role                 string     `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Id                   string     `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Email                string     `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string     `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string     `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Settings             []*Setting `protobuf:"bytes,7,rep,name=settings,proto3" json:"settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_385bde6a5715af9a, []int{4}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetNewuser() bool {
	if m != nil {
		return m.Newuser
	}
	return false
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetSettings() []*Setting {
	if m != nil {
		return m.Settings
	}
	return nil
}

// Setting user setting
type Setting struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enabled              bool     `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Setting) Reset()         { *m = Setting{} }
func (m *Setting) String() string { return proto.CompactTextString(m) }
func (*Setting) ProtoMessage()    {}
func (*Setting) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_385bde6a5715af9a, []int{5}
}
func (m *Setting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Setting.Unmarshal(m, b)
}
func (m *Setting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Setting.Marshal(b, m, deterministic)
}
func (dst *Setting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Setting.Merge(dst, src)
}
func (m *Setting) XXX_Size() int {
	return xxx_messageInfo_Setting.Size(m)
}
func (m *Setting) XXX_DiscardUnknown() {
	xxx_messageInfo_Setting.DiscardUnknown(m)
}

var xxx_messageInfo_Setting proto.InternalMessageInfo

func (m *Setting) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Setting) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Setting) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type Operation struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Operation            string   `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_385bde6a5715af9a, []int{6}
}
func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (dst *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(dst, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Operation) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Operation) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *Operation) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func init() {
	proto.RegisterType((*HealthcheckRequest)(nil), "dongfeng.svc.core.server.HealthcheckRequest")
	proto.RegisterType((*HealthcheckResponse)(nil), "dongfeng.svc.core.server.HealthcheckResponse")
	proto.RegisterType((*LoginRequest)(nil), "dongfeng.svc.core.server.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "dongfeng.svc.core.server.LoginResponse")
	proto.RegisterType((*User)(nil), "dongfeng.svc.core.server.User")
	proto.RegisterType((*Setting)(nil), "dongfeng.svc.core.server.Setting")
	proto.RegisterType((*Operation)(nil), "dongfeng.svc.core.server.Operation")
}

func init() {
	proto.RegisterFile("github.com/ilovelili/dongfeng/core/services/proto/api.proto", fileDescriptor_api_385bde6a5715af9a)
}

var fileDescriptor_api_385bde6a5715af9a = []byte{
	// 503 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0xab, 0xd3, 0x40,
	0x14, 0xb5, 0xdf, 0xed, 0xed, 0x7b, 0x5d, 0xdc, 0xf7, 0xd0, 0xa1, 0x88, 0xd4, 0x08, 0xda, 0x85,
	0x26, 0x50, 0x97, 0xe2, 0xc6, 0x85, 0x5f, 0x08, 0x42, 0xf4, 0x6d, 0xdc, 0x3c, 0xa6, 0xc9, 0x7d,
	0xe9, 0x60, 0x3a, 0x13, 0x67, 0xa6, 0x91, 0xf7, 0x03, 0xc5, 0xa5, 0x7f, 0x49, 0x66, 0x92, 0xb4,
	0x15, 0x09, 0xaf, 0xbb, 0x39, 0x87, 0x73, 0x0e, 0xf7, 0x9e, 0x70, 0x03, 0xaf, 0x32, 0x61, 0x37,
	0xbb, 0x75, 0x98, 0xa8, 0x6d, 0x24, 0x72, 0x55, 0x52, 0x2e, 0x72, 0x11, 0xa5, 0x4a, 0x66, 0x37,
	0x24, 0xb3, 0x28, 0x51, 0x9a, 0x22, 0x43, 0xba, 0x14, 0x09, 0x99, 0xa8, 0xd0, 0xca, 0xaa, 0x88,
	0x17, 0x22, 0xf4, 0x2f, 0x64, 0x8d, 0x2e, 0x34, 0x65, 0x12, 0x3a, 0x6d, 0xe8, 0xb4, 0xa4, 0x83,
	0x4b, 0xc0, 0xf7, 0xc4, 0x73, 0xbb, 0x49, 0x36, 0x94, 0x7c, 0x8f, 0xe9, 0xc7, 0x8e, 0x8c, 0x0d,
	0x22, 0xb8, 0xf8, 0x87, 0x35, 0x85, 0x92, 0x86, 0x90, 0xc1, 0x68, 0x4b, 0xc6, 0xf0, 0x8c, 0x58,
	0x67, 0xd1, 0x59, 0x4e, 0xe2, 0x06, 0x06, 0x33, 0x38, 0xfb, 0xa4, 0x32, 0x21, 0x9b, 0x80, 0xdf,
	0x5d, 0x38, 0xaf, 0x89, 0x83, 0xb7, 0x24, 0x6d, 0x84, 0x92, 0x8d, 0xb7, 0x86, 0xb8, 0x82, 0xfe,
	0xce, 0x90, 0x66, 0xdd, 0x45, 0x67, 0x39, 0x5d, 0x3d, 0x0a, 0xdb, 0x66, 0x0d, 0xaf, 0x0c, 0xe9,
	0xd8, 0x6b, 0xf1, 0x2b, 0x5c, 0x98, 0x5b, 0x63, 0x69, 0x7b, 0xbd, 0xd6, 0x8a, 0xa7, 0x09, 0x37,
	0x56, 0xc8, 0x8c, 0xf5, 0x16, 0xbd, 0xe5, 0x74, 0xf5, 0xa4, 0x3d, 0xe2, 0x73, 0x41, 0x9a, 0x5b,
	0xa1, 0x64, 0x8c, 0x95, 0xff, 0xcd, 0x91, 0x1d, 0xdf, 0xc2, 0x99, 0x4b, 0xbf, 0xde, 0x15, 0x29,
	0xb7, 0x64, 0x58, 0xff, 0xf4, 0xb8, 0xa9, 0x33, 0x5e, 0x55, 0x3e, 0xfc, 0x08, 0xb3, 0x1b, 0x2d,
	0x48, 0xa6, 0xfb, 0xa4, 0xc1, 0xe9, 0x49, 0xe7, 0x95, 0xb5, 0xce, 0x0a, 0x7e, 0x75, 0xa0, 0xef,
	0x16, 0x77, 0x05, 0x4a, 0xfa, 0xe9, 0x9b, 0x72, 0x05, 0x8e, 0xe3, 0x06, 0x22, 0x42, 0x5f, 0xab,
	0x9c, 0x7c, 0x81, 0x93, 0xd8, 0xbf, 0x71, 0x06, 0x5d, 0x91, 0xb2, 0x9e, 0x67, 0xba, 0x22, 0xc5,
	0x4b, 0x18, 0xd0, 0x96, 0x8b, 0x9c, 0xf5, 0x3d, 0x55, 0x01, 0xe7, 0x94, 0x7c, 0x4b, 0x6c, 0x50,
	0x39, 0xdd, 0x1b, 0xef, 0xc3, 0x90, 0x97, 0xdc, 0x72, 0xcd, 0x86, 0x9e, 0xad, 0x11, 0xbe, 0x86,
	0xb1, 0x21, 0xeb, 0x7a, 0x32, 0x6c, 0xe4, 0xd7, 0x79, 0xdc, 0xbe, 0xce, 0x97, 0x4a, 0x19, 0xef,
	0x2d, 0xc1, 0x3b, 0x18, 0xd5, 0x64, 0x3d, 0x9b, 0x5b, 0xa2, 0xe7, 0x67, 0x6b, 0xa6, 0xe8, 0x1e,
	0x4d, 0xc1, 0x60, 0x44, 0x92, 0xaf, 0x73, 0xaa, 0x96, 0x18, 0xc7, 0x0d, 0x0c, 0x34, 0x4c, 0xf6,
	0x65, 0xe1, 0x03, 0x18, 0xf9, 0x2f, 0x56, 0xe7, 0x4d, 0xe2, 0xa1, 0x83, 0x1f, 0x7c, 0xa6, 0x15,
	0x87, 0x4c, 0xf7, 0xc6, 0x87, 0x30, 0x51, 0x8d, 0xb3, 0xae, 0xe6, 0x40, 0xe0, 0x1c, 0xc6, 0x09,
	0xb7, 0x94, 0x29, 0x7d, 0x5b, 0x97, 0xb4, 0xc7, 0xab, 0x3f, 0x1d, 0xe8, 0xf1, 0x42, 0x60, 0x0e,
	0xd3, 0xa3, 0xbb, 0xc0, 0xe7, 0xed, 0x05, 0xfc, 0x7f, 0x54, 0xf3, 0x17, 0x27, 0xaa, 0xab, 0x83,
	0x09, 0xee, 0xe1, 0x37, 0x18, 0xf8, 0x1b, 0xc2, 0xa7, 0xed, 0xce, 0xe3, 0xab, 0x9b, 0x3f, 0xbb,
	0x53, 0xd7, 0x64, 0xaf, 0x87, 0xfe, 0xc7, 0xf0, 0xf2, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x18,
	0x87, 0x3a, 0x76, 0x57, 0x04, 0x00, 0x00,
}
