steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/dongfeng-core:1.0.$BUILD_ID', '.']
  timeout: '180s'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/dongfeng-core:1.0.$BUILD_ID']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/dongfeng-core', 'dongfeng-core=gcr.io/$PROJECT_ID/dongfeng-core:1.0.$BUILD_ID']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
substitutions:
  _COMPUTE_ZONE: 'asia-east1-a'
  _CONTAINER_CLUSTER: 'cloud-build-example'